import 'dart:convert';
import 'dart:io';

import 'package:first_project_flutter/models/dummy_model.dart';
import 'package:first_project_flutter/backend/laravel.dart';
import 'package:first_project_flutter/models/responsemodel.dart';
import 'package:first_project_flutter/pages/login.dart';
import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:http/http.dart' as http;




class Practice extends StatefulWidget {
  const Practice({super.key});

  @override
  State<Practice> createState() => _PracticeState();
}

class _PracticeState extends State<Practice> {

  apiResponse obj=new apiResponse();
 
//  Autogenerated obj= new Autogenerated();

//  Future<Autogenerated> getFact() async{

//   String url="https://catfact.ninja/fact";

//   final response= await http.get(Uri.parse(url));
//   var data=json.decode(response.body);
 

//   if(response.statusCode==200){
//     obj.fact=data.fact;
//     obj.length=data.length;



//   }
//   else{
//     print('server error');

//   }
//   return obj;
  



//  }
  @override
  Widget build(BuildContext context) {
    return 


    Scaffold(
      body:
        FutureBuilder<List<ResponseModel>>(
        future: apiResponse.fetchData(),
        builder: (BuildContext context, AsyncSnapshot<List<ResponseModel>> snapshot) {
          if (snapshot.connectionState == ConnectionState.waiting) {
            return Center(child: CircularProgressIndicator());
          } else if (snapshot.hasError) {
            return Text('Error: ${snapshot.error}');
          } else {
            return ListView.builder(
              itemCount: snapshot.data!.length,
              itemBuilder: (context, index) {
                final post = snapshot.data![index];
                return Container(
                            decoration: BoxDecoration(   
           color: Colors.blueAccent, 
           border: Border.all( 
             color: Colors.white, 
             width: 4.0, 
           )),
                  child: ListTile(
                    title: Text(post.name!),
                    subtitle: Text(post.email!),
                  ),
                );
              },
            );
          }
        },
      ),
    );
    
    

    
  }

//   
}

