import 'package:first_project_flutter/custom_helper/constants.dart';
import 'package:first_project_flutter/models/dummy_model.dart';
import 'package:first_project_flutter/models/responsemodel.dart';
import 'package:first_project_flutter/models/model_user_login.dart';
import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;
import 'dart:convert';

// ignore: camel_case_types
class apiResponse {
  static String baseUrl = AppConstants.baseUrl;
  Future<ModelUserLogin> getResponse(String email,String password) async {

    String apiUrl = '${baseUrl}api/user/login';
    try {
      var response = await http.post(Uri.parse(apiUrl),
      body: {
        "email": email,
        "password": password,
      },
      );
      if (response.statusCode == 200) {
        // Parse the JSON response
        final data= json.decode(response.body);
        return ModelUserLogin.fromJson(data);
      } else {
        return Future.error("Server Error");
      }
    } catch (e) {
      return Future.error(e);
    }
  }

  static apiUserRegistration(String name,String email,String password,String password_confirmation) async {
    
    String apiUrl = '${baseUrl}api/user/register';
    try {
      var response = await http.post(Uri.parse(apiUrl),
      body: {
        "name": name,
        "email": email,
        "password": password,
        "password_confirmation": password_confirmation,
      },
      );
      if (response.statusCode == 200) {
        return json.decode(response.body);
      } else {
        return "Server Error";
      }
    } catch (e) {
      print(e);
      return "Failed";
    }
  }

  Future<Autogenerated> getFact() async{

  String url="https://catfact.ninja/fact";

 print("chlgya");
  final response= await http.get(Uri.parse(url));
  var data=json.decode(response.body);
 print("bad ka chlgya");

  if(response.statusCode==200){
    var jsonResponse = json.decode(response.body);
    print(jsonResponse);
     return Autogenerated.fromJson(jsonResponse);
  // print(jsonResponse);

  }
  else{
    print('server error');
    return Future.error("glt");

  }
  // return obj;
  



 }


 Future<List<ResponseModel>> fetchData() async {
  // Replace this URL with your API endpoint
  final response = await http.get(Uri.parse('https://violent-wall-production.up.railway.app/api/user/test'));
  print(response.body);
  if (response.statusCode == 200) {
    // If the call to the server was successful, parse the JSON
    final data = json.decode(response.body) as List<dynamic>;
    return data.map((json) => ResponseModel.fromJson(json)).toList();
  } else {
    // If that call was not successful, throw an error.
    throw Exception('Failed to load data');
  }
}
  

  // Future<ModelUserLogin> Userlogin(String email,String password) async{
  //   // object
  //   ModelUserLogin? modelUserLogin;
  //   http.Response response= await http.post(
  //     Uri.parse('https://10.0.2.2:8000/api/user/login'),
  //     body: {
  //       "email": email,
  //       "password": password,
  //     },
  //   );
  //   var jsonResponse = json.decode(response.body);
  //   modelUserLogin = ModelUserLogin.fromJson(jsonResponse);
  //   print(modelUserLogin);
  //   return modelUserLogin;
  // }

}
