import 'package:first_project_flutter/backend/dummy_model.dart';
import 'package:first_project_flutter/backend/responsemodel.dart';
import 'package:first_project_flutter/model_user_login.dart';
import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;
import 'dart:convert';

// class ApiLogin extends StatefulWidget {
//   const ApiLogin({super.key});

//   @override
//   State<ApiLogin> createState() => _ApiLoginState();
// }

// class _ApiLoginState extends State<ApiLogin> {
//     Future<ModelUserLogin> Userlogin(String email,String password) async{
//     // object
//     ModelUserLogin? modelUserLogin;
//     http.Response response= await http.post(
//       Uri.parse('https://10.0.2.2:8000/api/user/login'),
//       body: {
//         "email": email,
//         "password": password,
//       },
//     );
//     var jsonResponse = json.decode(response.body);
//     modelUserLogin = ModelUserLogin.fromJson(jsonResponse);
//     print(modelUserLogin);
//     return modelUserLogin;
//   }
//   @override
//   Widget build(BuildContext context) {
//     return Scaffold();
//   }
// }

// ignore: camel_case_types
class apiResponse {
  Future<ModelUserLogin> getResponse(String email,String password) async {
    
    // local
    // String $baseUrl = 'https://127.0.0.1:8000/';
    
    // for emulator
    String $baseUrl = 'http://10.0.2.2:8000/';

    String apiUrl = '${$baseUrl}api/user/login';
    try {
      var response = await http.post(Uri.parse(apiUrl),
      body: {
        "email": email,
        "password": password,
      },
      );
      // Check if the request was successful (status code 200)
      if (response.statusCode == 200) {
        // Parse the JSON response
        print(response.body);
        final data= json.decode(response.body);
        return ModelUserLogin.fromJson(data);
      } else {
        return Future.error("Server Error");
      }
    } catch (e) {
      return Future.error(e);
    }
  }

  static apiUserRegistration(String name,String email,String password,String password_confirmation) async {
    
    // local
    // String $baseUrl = 'https://127.0.0.1:8082/';
    // String $baseUrl = 'http://192.168.0.67:8000/';
    
    // for emulator
    // String $baseUrl = 'http://10.0.2.2:8000/';

    // String apiUrl = '${$baseUrl}api/user/register';
    try {
      // var response = await http.post(Uri.parse(apiUrl),
      // body: {
      //   "name": name,
      //   "email": email,
      //   "password": password,
      //   "password_confirmation": password_confirmation,
      // },
      var response = await http.get(Uri.parse('https://catfact.ninja/fact'),
      // body: {
      //   "name": name,
      //   "email": email,
      //   "password": password,
      //   "password_confirmation": password_confirmation,
      // },
      );
      // Check if the request was successful (status code 200)
      if (response.statusCode == 200) {
        // Parse the JSON response
        print(response.body);
        return json.decode(response.body);
      } else {
        // Print an error message if the request was not successful
        print("server error");
        return "Server Error";
      }
    } catch (e) {
      print(e);
      return "Failed";
    }
  }

  Future<Autogenerated> getFact() async{

  String url="https://catfact.ninja/fact";

 print("chlgya");
  final response= await http.get(Uri.parse(url));
  var data=json.decode(response.body);
 print("bad ka chlgya");

  if(response.statusCode==200){
    var jsonResponse = json.decode(response.body);
    print(jsonResponse);
     return Autogenerated.fromJson(jsonResponse);
  // print(jsonResponse);

  }
  else{
    print('server error');
    return Future.error("glt");

  }
  // return obj;
  



 }


 Future<List<ResponseModel>> fetchData() async {
  // Replace this URL with your API endpoint
  final response = await http.get(Uri.parse('https://jsonplaceholder.typicode.com/posts'));
  if (response.statusCode == 200) {
    // If the call to the server was successful, parse the JSON
    final data = json.decode(response.body) as List<dynamic>;
    return data.map((json) => ResponseModel.fromJson(json)).toList();
  } else {
    // If that call was not successful, throw an error.
    throw Exception('Failed to load data');
  }
}
  

  // Future<ModelUserLogin> Userlogin(String email,String password) async{
  //   // object
  //   ModelUserLogin? modelUserLogin;
  //   http.Response response= await http.post(
  //     Uri.parse('https://10.0.2.2:8000/api/user/login'),
  //     body: {
  //       "email": email,
  //       "password": password,
  //     },
  //   );
  //   var jsonResponse = json.decode(response.body);
  //   modelUserLogin = ModelUserLogin.fromJson(jsonResponse);
  //   print(modelUserLogin);
  //   return modelUserLogin;
  // }

}
